local local_bin = vim.fn.expand("~/.local/bin")

if not vim.env.PATH:find(local_bin, 1, true) then
	vim.env.PATH = local_bin .. ":" .. vim.env.PATH
end

require("config.global_options")
require("config.filetype_overrides")
require("config.native_plugin_management")
require("config.mini_nvim_integration")
require("config.render_markdown")
require("config.plugin_setup_vscode_styling")
require("config.multi_cursor")
require("config.diagnostic_highlights")
require("config.oil")
require("config.neo_tree")
require("config.nvim_treesitter")
require("config.auto_tag")
require("config.gitsigns")
require("config.conform")
require("config.luasnip")
require("config.general_keymaps")
require("config.live_server")
require("config.tmux_navigation")
require("config.window_resize")
require("config.window_navigation")
require("config.buffer_tab_navigation")
require("config.move_lines")
require("config.search_indent")
require("config.format")
require("config.terminal")
require("config.lazygit_esc_fix")
require("config.navic")
require("config.nvim_cmp")
require("config.telescope")
require("config.lsp_setup_diagnostics")
require("config.diagnostic_signs")
require("config.diagnostic_toggle")
require("config.quickfix_diagnostics")
require("config.lsp_capabilities")
require("config.lsp_attach")
require("config.lua_ls")
require("config.emmet")
require("config.tailwind_css")
require("config.css")
require("config.enable_lsp_servers")
require("config.highlight_on_yank")
require("config.which_key")
require("config.lazygit")
require("config.local_llm_vectorcode_codecompanion")
require("config.codecompanion_keymaps")
require("config.ai_explain_current_lsp_error")
require("config.codecompanion_auto_hooks")
require("config.automatic_ai_buffer_cleaner")
require("config.codecompanion_buffer_settings")
require("config.global_codecompanion_focus")
