config_version = 14

[accessibility]
ui_scale = 0.95000000670552254

[bar.default]
background_opacity = 0.60999998636543751
end = [
    "media",
    "group:g1",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center",
    "session"
]
margin_ends = 20

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "network_tx", "network_rx", "tray", "temp" ]
    opacity = 1.0
    padding = 6.0

[hot_corners]
enabled = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-login-box@eDP-2" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 823.0
    cy = 847.0
    output = "eDP-1"
    placement_height = 1029.0
    placement_width = 1646.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.00006103515625
    cy = 987.75506591796875
    output = "eDP-2"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
font_family = "JetBrains Mono"
lang = "en"

[theme]
builtin = "Nord"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

[wallpaper.default]
path = "/home/rjaybernardo/Pictures/ROG-white.jpg"

[wallpaper.last]
path = "/home/rjaybernardo/Pictures/ROG-white.jpg"

[wallpaper.monitors.eDP-2]
path = "/home/rjaybernardo/Pictures/ROG-white.jpg"

[widget.battery]
color = "tertiary"
display_mode = "graphic"
hide_when_full = true
scale = 0.80000000000000004
show_label = false

[widget.brightness]
show_label = false

[widget.clipboard]
enabled = false

[widget.media]
enabled = false

[widget.network]
show_label = false

[widget.network_rx]
enabled = false
show_value = false
visualization = "graph"

[widget.network_tx]
enabled = false
label_show_units = false
show_value = false
visualization = "graph"

[widget.notifications]
enabled = false

[widget.temp]
show_glyph = false
visualization = "none"

[widget.volume]
show_label = false

[widget.wallpaper]
enabled = false